#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Autos")]
	public partial class DataAutosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAuto(Auto instance);
    partial void UpdateAuto(Auto instance);
    partial void DeleteAuto(Auto instance);
    #endregion
		
		public DataAutosDataContext() : 
				base(global::WpfApp1.Properties.Settings.Default.AutosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataAutosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAutosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAutosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAutosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Auto> Autos
		{
			get
			{
				return this.GetTable<Auto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Auto")]
	public partial class Auto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Kenteken;
		
		private decimal _Prijs;
		
		private int _Bouwjaar;
		
		private string _Merk;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKentekenChanging(string value);
    partial void OnKentekenChanged();
    partial void OnPrijsChanging(decimal value);
    partial void OnPrijsChanged();
    partial void OnBouwjaarChanging(int value);
    partial void OnBouwjaarChanged();
    partial void OnMerkChanging(string value);
    partial void OnMerkChanged();
    #endregion
		
		public Auto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kenteken", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Kenteken
		{
			get
			{
				return this._Kenteken;
			}
			set
			{
				if ((this._Kenteken != value))
				{
					this.OnKentekenChanging(value);
					this.SendPropertyChanging();
					this._Kenteken = value;
					this.SendPropertyChanged("Kenteken");
					this.OnKentekenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prijs", DbType="Decimal(8,2) NOT NULL")]
		public decimal Prijs
		{
			get
			{
				return this._Prijs;
			}
			set
			{
				if ((this._Prijs != value))
				{
					this.OnPrijsChanging(value);
					this.SendPropertyChanging();
					this._Prijs = value;
					this.SendPropertyChanged("Prijs");
					this.OnPrijsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bouwjaar", DbType="Int NOT NULL")]
		public int Bouwjaar
		{
			get
			{
				return this._Bouwjaar;
			}
			set
			{
				if ((this._Bouwjaar != value))
				{
					this.OnBouwjaarChanging(value);
					this.SendPropertyChanging();
					this._Bouwjaar = value;
					this.SendPropertyChanged("Bouwjaar");
					this.OnBouwjaarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Merk", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Merk
		{
			get
			{
				return this._Merk;
			}
			set
			{
				if ((this._Merk != value))
				{
					this.OnMerkChanging(value);
					this.SendPropertyChanging();
					this._Merk = value;
					this.SendPropertyChanged("Merk");
					this.OnMerkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
